### ISSUE TITLE
Can't use finally on connect?

### ISSUE THREAD

**Issue by LordZardeck** [vitaly-t/pg-promise#144]
I want to use `.finally()` to close out the connection, but i get errors trying to use it on `.connect()`

following the example code:

```js
'use strict';

const connectionDetails = {
	host: process.env.RDS_HOST,
	port: process.env.RDS_PORT || 5432,
	database: process.env.RDS_DATABASE,
	user: process.env.RDS_USER,
	password: process.env.RDS_PASSWORD
};

const pg = require('pg-promise')();

console.log(connectionDetails);

exports.handler = (event, context) => {
	const db = pg(connectionDetails);

	var sco; // shared connection object;
	db.connect()
		.then(function (obj) {
			sco = obj; // save the connection object;
			// find active users created before today:
			return sco.query('select * from users where active=$1 and created < $2',
				[true, new Date()]);
		})
		.then(function (data) {
			console.log(data); // display all the user details;
		})
		.catch(function (error) {
			console.log(error); // display the error;
		})
		.finally(function () {
			if (sco) {
				sco.done(); // release the connection, if it was successful;
			}
		});
};
```

I get the following error:

```
/path/to/project/lambdas/gatewayacl_get_permissible_actions/index.js:32
                .finally(function () {
                        ^

TypeError: db.connect(...).then(...).then(...).catch(...).finally is not a function
    at exports.handler (/path/to/project/lambdas/gatewayacl_get_permissible_actions/index.js:32:11)
    at Lambda._runHandler (/home-directory/.nvm/versions/node/v6.1.0/lib/node_modules/node-lambda/lib/main.js:93:7)
    at Lambda.run (/home-directory/.nvm/versions/node/v6.1.0/lib/node_modules/node-lambda/lib/main.js:49:8)
    at Command.<anonymous> (/home-directory/.nvm/versions/node/v6.1.0/lib/node_modules/node-lambda/bin/node-lambda:89:12)
    at Command.listener (/home-directory/.nvm/versions/node/v6.1.0/lib/node_modules/node-lambda/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/User
```

**Comment by LordZardeck** [comment]
Nvrm, forgot to specify the `bluebird` library, noticed the native Library doesn't have `.finally()`

**Comment by vitaly-t** [comment]
Why do you want to use `connect` for executing query? It has been depreciated in that context. You should use [Tasks] instead, they are way better.

[Tasks]:https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#tasks
