### ISSUE TITLE
Trailing $ in any row value makes insert fail

### ISSUE THREAD

**Issue by boris-hocde** [vitaly-t/pg-promise#211]
Hi.

I am quite new to pg-promise (and node.js in general), so please forgive me if I have missed something...
When I try to insert a row, if any of its string value ends by a dollar ($), the statement fails.

```js
var properties = require('./../../config/properties.json');
var bunyan = require('bunyan');
var promise = require('bluebird');
var pgpLib = require('pg-promise');

// Load and configure logger
var logger = bunyan.createLogger({ name: 'integration', level: process.argv[2] || properties.logLevel });
logger.info(`Logger loaded (logLevel: ${properties.logLevel})`);

// Database Adapter
var pgp = pgpLib({
    promiseLib: promise
});
var db = pgp(properties.dbconf);

// Insert row
var insert = 'INSERT INTO test_dollar (id, content) VALUES (${id}, ${content})';
var row = {
    id: 1,
    content: 'Some content ending by $'
};

db.none(insert, row);
```

It produces the following output:
```
Unhandled rejection error: unterminated quoted string at or near "'Some content ending by ))"
    at Connection.parseE (/.../node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/.../node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/.../node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

And Postgresql reports the following query:
```
2016-09-21 12:28:37 UTC ERROR:  unterminated quoted string at or near "'Some content ending by ))" at character 50
2016-09-21 12:28:37 UTC STATEMENT:  INSERT INTO test_dollar (id, content) VALUES (2, 'Some content ending by ))
```

My config:
* Node v6.6.0
* PostgreSQL 9.5.4
* Pg-promise 1.4.4

Thank you!

**Comment by vitaly-t** [comment]
Interesting... I will check it later this evening.

**Comment by vitaly-t** [comment]
I did some testing....

Thought you were kidding quoting `pg-promise` version as 1.4.4, but you weren't. That version did indeed have the issue you described.

The real question - what are you doing using such a pre-historic version of the library? :) The current version is 5.3.3.

And that issue was fixed ages ago. Just upgrade the library.
