### ISSUE TITLE
WARNING: Invalid property 'host' in initialization options.

### ISSUE THREAD

**Issue by lsimmons2** [vitaly-t/pg-promise#256]
Sorry if I'm missing something obvious here, or let me know if I should provide more info, but running the following code

```
import pgp from 'pg-promise'

let cn = {
    host: 'localhost',
    port: 5432,
    database: 'states',
    user: 'my_username',
    password: 'my_password'
};

let db = pgp(cn);
```

with `node v7.2.1 and v7.1.0` (`nvm`) and `pg-promise v5.5.0` I'm getting the following error
```
WARNING: Invalid property 'host' in initialization options.
    at Object.<anonymous> (/Users/leosimmons/cs/states-app/server/routes.js:13:10)
    at loader (/Users/leosimmons/.nvm/versions/node/v7.2.1/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/leosimmons/.nvm/versions/node/v7.2.1/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
```

I get it when I run with `babel-node` and with `node` after transpiling.

**Comment by vitaly-t** [comment]
The first call is with initialization options, the second one with the database connection, [as per documentation](https://github.com/vitaly-t/pg-promise#initialization).

**Comment by lsimmons2** [comment]
Ahh gotcha, I missed that you still have to call the initialization method even if you're not using initialization options.
Thanks!
