### ISSUE TITLE
Query with regex giving errors

### ISSUE THREAD

**Issue by allenyin55** [vitaly-t/pg-promise#298]
Hi, I am trying to do a regex query that will return all the words that start with a certain string. It works fine in posgresql, but gives me errors with this library.

My code:

function searchWords(req, res, next){

  // req.body.word = "you"
  db.any("SELECT * FROM dictionary WHERE word ~ '^($1).*'", req.body.word)
    .then((data) => {

      res.status(200)
              .json({
                  status: 'success',
                  data: data,
                  message: 'searched words!'
              });
      })
      .catch(function (err) {
        console.log(err)
        return next(err);
      });

}

my error:

{ error: syntax error at "you" or around
    at Connection.parseE (C:\Users\Allen\Desktop\Code_Stuff\Webdev\readingWithAnnie\readingWithAnnieAPI\node_modules\pg-promise\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (C:\Users\Allen\Desktop\Code_Stuff\Webdev\readingWithAnnie\readingWithAnnieAPI\node_modules\pg-promise\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (C:\Users\Allen\Desktop\Code_Stuff\Webdev\readingWithAnnie\readingWithAnnieAPI\node_modules\pg-promise\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 114,
  severity: 'erro',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '44',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'src\\backend\\parser\\scan.l',
  line: '1053',
  routine: 'scanner_yyerror' }

Thanks!

**Comment by vitaly-t** [comment]
You formatting is wrong. It must be one of these three, whichever you like better:

```js
db.any("SELECT * FROM dictionary WHERE word ~ $1", '^(' + req.body.word + ').*')
```

```js
db.any("SELECT * FROM dictionary WHERE word ~ '^($1#).*'", req.body.word)
```

```js
db.any("SELECT * FROM dictionary WHERE word ~ '^($1:value).*'", req.body.word)
```

**Comment by allenyin55** [comment]
Thanks! I should mention only the first one works for me. Not sure why.

**Comment by vitaly-t** [comment]
@allenyin55 check what you are getting in the other ones and publish here :wink:

For that use this kind of code:

```js
var format = pgp.as.format;

var s1 = format("SELECT * FROM dictionary WHERE word ~ '^($1#).*'", req.body.word);
console.log('s1:', s1);

var s2 = format("SELECT * FROM dictionary WHERE word ~ '^($1:value).*'", req.body.word);
console.log('s2:', s2);
```

Then we can see what is wrong there ;)
