### ISSUE TITLE
"Invalid username" in what I really think is a valid postgres URL

### ISSUE THREAD

**Issue by retorquere** [vitaly-t/pg-promise#351]
I'm getting "Invalid username" in what I really think is a valid postgres URL (`postgres://user:password@pgsvr-cvrmtoolbox.postgres.database.azure.com/dbname`). When I pass it through https://github.com/iceddev/pg-connection-string/blob/master/index.js it parses cleanly, but using this script:

```
'use strict';

const pgp = require('pg-promise')();

const db = pgp('postgres://user:password@pgsvr-cvrmtoolbox.postgres.database.azure.com/dbname');

db.any('SELECT count(*) FROM cvrm.clients')
  .then(function(data) {
    // success;
    console.log(data);
  })
  .catch(function(error) {
    console.log(error);
    // error;
  });
```
yields 

```
{ error: Invalid Username specified. Please check the Username and retry connection. The Username should be in <user name@hostname> format.
    at Connection.parseE (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'error',
  length: 187,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '481',
  routine: 'ClientAuthentication' }
```

It's not an authentication failure, because if I connect to another PG database with invalid credentials (`postgres://user:password@localhost/dbname`), I get:

```
{ error: password authentication failed for user "user"
    at Connection.parseE (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'error',
  length: 100,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '307',
  routine: 'auth_failed' }
```

If I stick in my valid localhost URL (`postgres://actualuser:actualpassword@localhost/actualdb`), I get:

```
[ anonymous { count: '10000' } ]
```

**Comment by vitaly-t** [comment]
What user name are you passing in? Can you show the actual connection string that you are using?

**Comment by retorquere** [comment]
I get these errors with the connection strings as listed, but I can get you the actual URLs if I can send them to you in private (I'd rather not put live passwords in the issue).

**Comment by vitaly-t** [comment]
I don't know, the error comes from your azure setup. Try changing it to configuration object, i.e. from 

```
postgres://user:password@pgsvr-cvrmtoolbox.postgres.database.azure.com/dbname
```
to
```js
var config = {
  server: 'pgsvr-cvrmtoolbox.postgres.database.azure.com',
  database: 'dbname',
  user: 'user',
  password: 'password'
};
```

**Comment by retorquere** [comment]
If you say it's outside then it's outside, but I get the same different errors when I pass a config object; this modified script:

```
// testpg.js
const pgp = require('pg-promise')();
const parse = require('pg-connection-string').parse;

const url = process.argv[2];
var config = parse(url);
config.server = config.host;
var db = pgp(config);

db.any('SELECT count(*) FROM cvrm.clients')
  .then(function(data) { console.log('url:', url, 'config:', JSON.stringify(config), 'data:', JSON.stringify(data)); })
  .catch(function(error) { console.log('url:', url, 'config:', JSON.stringify(config), 'error:', error); })
```

when run as
```
for u in postgres://emile:emile@localhost/emile postgres://invalid:emile@localhost/emile postgres://emile:emile@pgsvr-cvrmtoolbox.postgres.database.azure.com/emile; do
  node testpg.js $u
done
```

shows

```
url: postgres://emile:emile@localhost/emile config: {"port":null,"host":"localhost","database":"emile","user":"emile","password":"emile","server":"localhost"} data: [{"count":"10000"}]
url: postgres://invalid:emile@localhost/emile config: {"port":null,"host":"localhost","database":"emile","user":"invalid","password":"emile","server":"localhost"} error: { error: password authentication failed for user "invalid"
    at Connection.parseE (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'error',
  length: 103,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '307',
  routine: 'auth_failed' }
url: postgres://emile:emile@pgsvr-cvrmtoolbox.postgres.database.azure.com/emile config: {"port":null,"host":"pgsvr-cvrmtoolbox.postgres.database.azure.com","database":"emile","user":"emile","password":"emile","server":"pgsvr-cvrmtoolbox.postgres.database.azure.com"} error: { error: Invalid Username specified. Please check the Username and retry connection. The Username should be in <user name@hostname> format.
    at Connection.parseE (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/emile/github/cvrm/node_modules/pg-promise/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'error',
  length: 187,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '481',
  routine: 'ClientAuthentication' }
```
Is pg-promise passing on an error from a lower library (and if so, which)? I don't understand why one call gets me an expected "password authentication failed", and the other an "Invalid Username specified". Are those specific errors generated outside pg-promise?

**Comment by vitaly-t** [comment]
Any error that you are getting is outside of this library.

When you are using a connection string, it is parsed via [pg-connection-string](https://github.com/iceddev/pg-connection-string), which converts into into the config object. And the config object is processed by the [underlying driver](https://github.com/brianc/node-postgres).

**Comment by retorquere** [comment]
OK, super, I've confirmed the error with the underlying library, I'll post the error there.

**Comment by vitaly-t** [comment]
Cool. You can use this issue for reference, though I'm closing it here, because as stated earlier, it is out of scope for this library.

**Comment by retorquere** [comment]
Oops sorry, I see it now, it's `pgp.pg`

**Comment by vitaly-t** [comment]
@retorquere Only through a manual connection, method [connect](http://vitaly-t.github.io/pg-promise/Database.html#.connect), should be used with care, ad only in special cases. Other than that, you should not use it.

Why do you need the connection object anyway?

**Comment by retorquere** [comment]
Still testing the azure problem. It's azure-specific, but all my scripts use pg-promise, so I'd like to keep them as-is where I can but debug by looking lower in the stack when I need to.

**Comment by vitaly-t** [comment]
If you have any azure-specific problems, then all the errors you get from the driver are the same errors you will get from pg-promise, so going lower isn't strictly necessary ;)

**Comment by vitaly-t** [comment]
@retorquere as for checking connectivity via pg-promise, see: https://stackoverflow.com/questions/36120435/verify-database-connection-with-pg-promise-when-starting-an-app

**Comment by retorquere** [comment]
Right on the former, thanks on the latter!
