### ISSUE TITLE
Readable Stream example documentation wanted

### ISSUE THREAD

**Issue by Jonke** [vitaly-t/pg-promise#434]
if the stream is a  Readable({ objectMode: true }); 
 the 'second' call don't have any connection to the db.  

```
import * as fs from "fs";
import { ISpex, IStream, TSequenceResult } from "spex";
import * as spexLib from "spex";
import { Readable, Stream } from "stream";
import * as XmlStream from "xml-stream";
import { db, IExtensions } from "./db";


const spex: spexLib.ISpex = spexLib(Promise);

type BatchError = typeof spex.errors.BatchError;
function parsePoint(rs: Readable, pathToXML: string) {
  const stream = fs.createReadStream(pathToXML);

  const xml = new XmlStream(stream);

  xml.on("endElement: point", function(item: any) {
rs.push(item);
});
xml.on("end", (event: any) => {
   
    rs.push(null);
  });
return rs;
}


function receiver(_: any, data: any) {
  
  function source(index: number) {
    if (index < data.length) {
      return data[index];
    }
  }

  function dest(index: number, mdata: any) {
  
    const p = this.point.insert(mdata.point);
   
      p.catch((e: any) => {
          console.error("inner-err", e);
        });
 
    return p;
  
  }
  return this.sequence(source, { dest });
}

const streamRead = spex.stream.read;
const rs = new Readable({ objectMode: true });
rs._read = function() {};
const pp: Readable = parsePoint(rs, pathToXML);
  
  
  db
    .task("massive-insert", t => {
      return streamRead.call(t, rs, receiver);
    })
    .then(data => {
    
      console.log(data);

      console.log("Total batches:", data.total, ", Duration:", data.duration, "ms");
    })
    .catch(error => {
    
      console.log(error);
    });
```
 
The lines 
```
11:00:09 task(massive-insert)/end; duration: 05.956, success: true
11:00:09 disconnect(jf@jf)
```

from the output of the diagnostics  surprise  me.
Because the second part has been invoked by the `return this.sequence(source, { dest });` at that point but is still running.

```
11:00:09 task(massive-insert)/end; duration: 05.956, success: true
11:00:09 disconnect(jf@jf)
{ calls: 2, reads: 548, length: 0, duration: 5955 }
Total batches: undefined , Duration: 5955 ms
11:00:09 error: Querying against a released or lost connection.
      
inner-err Error: Querying against a released or lost connection.
    at getContext (node_modules/pg-promise/lib/query.js:214:25)
    at notifyReject (node_modules/pg-promise/lib/query.js:226:29)
    at Query.ctx.db.client.query [as callback] (node_modules/pg-promise/lib/query.js:197:22)
    at Query.handleReadyForQuery (node_modules/pg/lib/query.js:126:10)
    at Connection.<anonymous> (node_modules/pg/lib/client.js:163:19)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (node_modules/pg/lib/connection.js:118:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
```

**Comment by Jonke** [comment]
After some more tries I got to the conclusion that the example of streaming from "Learn by example"  is if not wrong but maybe a bit misleading.

I'm sure there is some things that says why **A** work and **C** don't work in an obvious way but I wouldn't mind a bit more info in the example.

This receiver function works
**A**
```
function receiver2(index: number, data: any, delay: number) {
  console.log("RECEIVED:", index, data.length, delay);
  return this.sequence((n: number) => {
    if (n < data.length) return this.point.insert(data[n].point);
  });
} 
```

This fails (with lost connection)
**B**
```
function receiver2(index: number, data: any, delay: number) {
  console.log("RECEIVED:", index, data.length, delay);
return t.batch(data.map(x => this.point.insert(x.point)));
 
} 
```

This fails( with lost connection)
**C**
```
function receiver(_: any, data: any) {
  
  function source(index: number) {
    if (index < data.length) {
      return data[index];
    }
  }

  function dest(index: number, mdata: any) {
  
    const p = this.point.insert(mdata.point);
   
      p.catch((e: any) => {
          console.error("inner-err", e);
        });
 
    return p;
  
  }
  return this.sequence(source, { dest });
}
```

**Comment by vitaly-t** [comment]
When you are getting `Querying against a released or lost connection.`, it means you are executing a query after the task/transaction has finished.

Here's a more detailed example of working with streams: [Data Imports](https://github.com/vitaly-t/pg-promise/wiki/Data-Imports).

Other than that, I can do only very limited support while on holidays till Dec 18th.
