### ISSUE TITLE
Insert 42601 ERROR

### ISSUE THREAD

**Issue by kevinjuliano1020** [vitaly-t/pg-promise#569]
I am trying to insert a new record and return the inserted ID but I am getting an error. 

Here's how I did it.
```
var fields = "type, save_type, share_opt, name, query, user_id, link, security_code, sched_type, notes, share_email, published";

var $n = "$1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $12";

var items = [ 'trademark',
  3,
  'share with link',
  'test title',
  'WORDS=BLAST AND GS=CANDY',
  1,
  '/savedtrademark/s51yrqE',
  's51yrqE',
  '2',
  'test',
  'test@gmail.com',
  1 ];

var qstring = "INSERT INTO users.save_result ("+fields+") VALUES("+$n+") RETURNING id";

db.one(qstring, items)
    .then((data) => {
        console.log(data);
    })
    .catch(error => {
      console.log(error);
	});
```
ERROR:
```
error: syntax error at or near "3"
    at Connection.parseE (/media/kevin/Kevin2017/work/ptodirect/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/media/kevin/Kevin2017/work/ptodirect/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/media/kevin/Kevin2017/work/ptodirect/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '166',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1128',
  routine: 'scanner_yyerror' }
```
I also checked the column types on the table and they are correct,  I don't know what I'm missing here. 

* Version of pg-promise: ^8.5.2
* OS type (Linux/Windows/Mac): Ubuntu 18.x
* Version of Node.js: 10.13.0

**Comment by kevinjuliano1020** [comment]
Sorry, I am just missing "," on parameters
