### ISSUE TITLE
Access data tables named with "-"

### ISSUE THREAD

**Issue by epm-bt** [vitaly-t/pg-promise#587]
### Expected behavior
I'd like to build a REST service which can accept requests with fields containing dashes ("-"), as the Postgre tables name contain these characters.

### Actual behavior
Will fail with the following error message:
```
syntax error at or near "-"

error: syntax error at or near "-"
    at Connection.parseE (/home/path/to/testAPI/node-postgres-promises/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/path/to/testAPI/node-postgres-promises/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/path/to/testAPI/node-postgres-promises/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
```

### Steps to reproduce
I've got a properly set up Node.js code where it accepts requests with id without "-" and fetch data at the table... This is how the module are configured.
```
function getFeed(req, res, next) {
db.any('select * from ' + req.params.id, req.params.id)
    .then(function (data) {
      res.status(200)
        .json({
          status: 'success',
          data: data,
          message: 'Retrieved sensors'
        });
    })
    .catch(function (err) {
      return next(err);
    });
}
```

* Version of pg-promise: 5
* OS type (Linux/Windows/Mac): Ubuntu 18.04
* Version of Node.js: v11.10.0

**Comment by vitaly-t** [comment]
You should never concatenate queries manually. And for table names there are [Named Parameters].

Also, we do not support pg-promise as ancient as v5 anymore.

[Named Parameters]:https://github.com/vitaly-t/pg-promise#named-parameters

**Comment by epm-bt** [comment]
Thanks, @vitaly-t, it was useful!
