### ISSUE TITLE
Error: Connection terminated by user

### ISSUE THREAD

**Issue by sathishkumarsoundharajan** [vitaly-t/pg-promise#601]
### Expected behavior

Should not throw an error OR way to find what is causing error with stack / how to handle this 

### Actual behavior

Getting Error: Connection terminated by user from pg / pg-promise

### Steps to reproduce

Really not able to reproduce, because this only happens if i run 1000 of test cases using mocha.

### Environment

* Version of pg-promise: 6.10.3
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: v6.11.5

**Comment by vitaly-t** [comment]
> Should not throw an error OR way to find what is causing error with stack / how to handle this

This is not a clear description of what the problem is.

> Really not able to reproduce, because this only happens if i run 1000 of test cases using mocha.

And this doesn't help either at all.

Please either improve on the issue report, or I will have to close it as unsubstantiated.

**Comment by sathishkumarsoundharajan** [comment]
@vitaly-t Apologies, the expected behaviour here is i should not be getting this error as my database connection is open through the test case execution. So i am not able to figure out why this error is being triggered.

About reproducing this issue, if i am able to provide repro case i would. But this happens very sporadically and at very different times / files of test case execution. As this is closed source i won't be post it.

I know clearly, this is not useful for you. I just need some pointers / ways to debug this from pg-promise perspective. 

Yes, please close the issue the above clarification is not useful. i will find a way to debug more and create a new issue. 

Thanks

**Comment by sathishkumarsoundharajan** [comment]
Here is the full stack trace which i am getting when running the test cases 

```
Abnormal client.end() call, due to invalid code or failed server connection.
    at Pool._remove (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-pool/index.js:161:12)
    at Timeout.setTimeout (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-pool/index.js:44:12)

Abnormal client.end() call, due to invalid code or failed server connection.
    at Pool._remove (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-pool/index.js:161:12)
    at Timeout.setTimeout (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-pool/index.js:44:12)

Abnormal client.end() call, due to invalid code or failed server connection.
    at Pool._remove (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-pool/index.js:161:12)
    at Client.idleListener (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-pool/index.js:75:10)
    at Connection.connectedErrorHandler (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-promise/node_modules/pg/lib/client.js:134:10)
    at Socket.<anonymous> (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-promise/node_modules/pg/lib/connection.js:71:10)
    at Connection.end (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-promise/node_modules/pg/lib/connection.js:313:22)
    at global.Promise (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-promise/node_modules/pg/lib/client.js:410:23)
    at Client.end (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-promise/node_modules/pg/lib/client.js:409:12)
    at Client.client.end.doNotCall [as end] (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-promise/lib/connect.js:114:17)
    at Pool._remove (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-pool/index.js:161:12)
    at Timeout.setTimeout (/Users/ecom-sathish.kumar/Desktop/Code/service/node_modules/pg-pool/index.js:44:12)
```

@vitaly-t

**Comment by vitaly-t** [comment]
This is the known and documented behavior when the connection is suddenly lost. Are you contesting that it shouldn't do so?

**Comment by sathishkumarsoundharajan** [comment]
I am not @vitaly-t . Like i said before i just need some pointers / ways to debug this connection lost. Is there a way like enabling DEBUG statements to debug the library / some other ways to debug.

**Comment by vitaly-t** [comment]
There is nothing specific to this library about debugging it. Generic node.js app debugging is all it takes.

**Comment by sathishkumarsoundharajan** [comment]
Thanks @vitaly-t .
