### ISSUE TITLE
Column name is lowercased at insert

### ISSUE THREAD

**Issue by faroutchris** [vitaly-t/pg-promise#666]
### Expected behavior

The following query should insert a new row into my table.
```
insert into "notifications"("sender","receiver","sentAt","message") 
values('Storuman lasarett',
'0707905582',
'2019-11-05T17:03:00.809Z',
'Your package has arrived.')
RETURNING id, sender, receiver, message, sentAt, createdAt
```

The table is defined as following:
```
CREATE TABLE notifications (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    receiver character varying(256) NOT NULL,
    sender character varying(256) NOT NULL,
    message text NOT NULL,
    "sentAt" timestamp without time zone NOT NULL,
    "createdAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
```

### Actual behavior

I get the following error which references the column `sentat` when it is defined as `sentAt`:
```
error: column "sentat" does not exist
    at Connection.parseE (/Users/christo/repos/brevduvor/packages/api/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/Users/christo/repos/brevduvor/packages/api/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/Users/christo/repos/brevduvor/packages/api/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  name: 'error',
  length: 174,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Perhaps you meant to reference the column "notifications.sentAt".',
  position: '248',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3294',
  routine: 'errorMissingColumn'
}
```

### Steps to reproduce

Here's how I create the query:
```
export async function createNew(notification: NotificationInput) {
  const query = pgp.helpers.insert(
    {
      ...notification,
    },
    undefined,
    'notifications'
  ) + 'RETURNING id, sender, receiver, message, sentAt, createdAt'

  return db.one(query)
}
```

### Environment

* Version of pg-promise: 9.2.1
* OS type (Linux/Windows/Mac): MacOS 10.14.6 
* Version of Node.js: v12.9.1

**Comment by faroutchris** [comment]
Issue seems to persist when running this as raw queries in postgres. Guessing this has nothing to do with the pg-promise library.

**Comment by faroutchris** [comment]
Replacing the query at `RETURNING ... sentAt` with `RETURNING *` makes it work (if anyone with a similar issue lands on this page). 

I don't know if I'm missing something obvious or if there is some bug in postgres but I'm not prodding any further into this issue.

**Comment by vitaly-t** [comment]
@faroutchris The bug is on your side, not the Postgres server :)

Replace this:

```sql
RETURNING id, sender, receiver, message, sentAt, createdAt
```
with this:

```sql
RETURNING id, sender, receiver, message, "sentAt", createdAt
```

And it will work, because `sentAt` needs to be double-quoted, for the camel-case to be recognized correctly. You should get familiar with how camel cases work in Postgres.

**Comment by faroutchris** [comment]
Thanks!
