### ISSUE TITLE
Received protocol request 'E' for portal while in PortalSuspended state for portal

### ISSUE THREAD

**Issue by RoAsHrOaSh** [vitaly-t/pg-promise#691]
I'll begin by saying I'm not sure the problem is related to this wonderful library, but I think it's worth sharing it as nothing else worked for me so far.

I'm trying to run a query from node.js and I'm getting the following error:
Received protocol request 'E' for portal '' while in PortalSuspended state for portal '<unnamed portal 14>'.

call stack:
error: Received protocol request 'E' for portal '' while in PortalSuspended state for portal '<unnamed portal 14>'.
    at Connection.parseE (C:\ws\IGServer\node_modules\pg\lib\connection.js:604:13)
    at Connection.parseMessage (C:\ws\IGServer\node_modules\pg\lib\connection.js:403:19)
    at Socket.<anonymous> (C:\ws\IGServer\node_modules\pg\lib\connection.js:123:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

important to say that I don't use the pg lib directly, only through pg-promise.
also, when I run the query on Workbench I get results and everything seems to be fine.
I tried to revert my Redshift version on AWS, but it didn't seem to solve this issue.

Will appreciate any help with it.

* Version of pg-promise: 7.5.2 (reproduced also on 10.4.0)
* OS type (Linux/Windows/Mac): Linux + Windows
* Version of Node.js: 10.15.3

**Comment by vitaly-t** [comment]
You should open this against [the driver](https://github.com/brianc/node-postgres). It is not an issue with this library.

**Comment by vitaly-t** [comment]
[Issued opened against the driver](https://github.com/brianc/node-postgres/issues/2055).
