### ISSUE TITLE
Help Needed - error: column does not exist

### ISSUE THREAD

**Issue by RayKahn** [vitaly-t/pg-promise#719]
### Expected behavior
Update multiple records

### Actual behavior
A `42703` error is thrown.

```
error: column v.locationid does not exist
    at Connection.parseE (/Users/localadmin/myprojects/spyder-location/node_modules/pg-promise/node_modules/pg/lib/connection.js:581:48)
    at Connection.parseMessage (/Users/localadmin/myprojects/spyder-location/node_modules/pg-promise/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/Users/localadmin/myprojects/spyder-location/node_modules/pg-promise/node_modules/pg/lib/connection.js:116:22)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
From previous event:
    at promise (/Users/localadmin/myprojects/spyder-location/node_modules/pg-promise/lib/promise-parser.js:30:20)
    at Database.$query (/Users/localadmin/myprojects/spyder-location/node_modules/pg-promise/lib/query.js:145:12)
    at Database.<anonymous> (/Users/localadmin/myprojects/spyder-location/node_modules/pg-promise/lib/query.js:263:23)
    at /Users/localadmin/myprojects/spyder-location/node_modules/pg-promise/lib/database.js:329:42
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)
From previous event:
    at Database.query (/Users/localadmin/myprojects/spyder-location/node_modules/pg-promise/lib/database.js:327:14)
    at Database.obj.none (/Users/localadmin/myprojects/spyder-location/node_modules/pg-promise/lib/database.js:502:30)
    at Object.updateLocation (/Users/localadmin/myprojects/spyder-location/src/location/location-persistence-pg.js:209:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.updateLocation (/Users/localadmin/myprojects/spyder-location/src/location/location-service.js:582:26)
    at async updateLocation (/Users/localadmin/myprojects/spyder-location/src/location/location-controller.js:90:18) {
  name: 'error',
  length: 200,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Perhaps you meant to reference the column "t.locationid" or the column "v.locationId".',
  position: '1291',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3377',
  routine: 'errorMissingColumn'
}
```

### Steps to reproduce

```
const bb = require('bluebird');
bb.config({longStackTraces: true});

const postgresConfig = {/** Config here **/};
const pgp = require('pg-promise')({
	capSQL: true, 
	promiseLib: bb
});
const db = pgp(postgresConfig);

```

`
values = PostgresUtil.parseCategoryDataAsMap(pFormParams.vehicleCategories, locationId);
`

Which produces the following:
```
[
    {
      locationId: '5d93ec2d80cae4108c9f4236',
      categoryId: '5c49f4cf2f6f74075c67ed9b',
      dayOfMonth: '2019-10-09',
      capacity: 2000
    },
    {
      locationId: '5d93ec2d80cae4108c9f4236',
      categoryId: '5c49f4cf2f6f74075c67ed9b',
      dayOfMonth: '2019-10-05',
      capacity: 2000
    }
]
```
```
const cs = new pgp.helpers.ColumnSet([
'?locationId', '?categoryId', ...locationConstants.LOCATION_CAPACITY_PG_KEYS.slice(2)
], 
{table: 'location_vehicle_category_capacity'}
);
```

Which returns the following
```
ColumnSet {
    table: "location_vehicle_category_capacity"
    columns: [
        Column {
            name: "locationId"
            cnd: true
        }
        Column {
            name: "categoryId"
            cnd: true
        }
        Column {
            name: "dayOfMonth"
        }
        Column {
            name: "capacity"
        }
    ]
}
```
```
const update = pgp.helpers.update(values[0], cs) + ' WHERE v.locationId = t.locationId AND v.categoryId =  t.category_id';
```

Which returns the following:

```
UPDATE "location_vehicle_category_capacity" AS t SET "dayOfMonth"=v."dayOfMonth","capacity"=v."capacity" FROM (VALUES('5d93ec2d80cae4108c9f4236','5c49f4cf2f6f74075c67ed9b','2019-10-09',2000),('5d93ec2d80cae4108c9f4236','5c49f4cf2f6f74075c67ed9b','2019-10-05',2000)) AS v("locationId","categoryId","dayOfMonth","capacity") WHERE v.locationId = t.locationId AND v.categoryId =  t.category_id
```

And table schema is:

```
CREATE Table location_vehicle_category_capacity (
  id serial PRIMARY KEY,
  locationId varchar NOT NULL,
  category_id varchar NOT NULL,
  dayOfMonth TEXT not null,
  capacity int not null,
);
```
### Environment

* Version of pg-promise: latest
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 12.15.0

**Comment by vitaly-t** [comment]
You should read about how PostgreSQL treats camel-case column names. That's your only problem here, missing quotations around column names in the condition.

```sql
 WHERE v."locationId" = t."locationId" AND v."categoryId" =  t.category_id
```
