### ISSUE TITLE
Odd stack trace when passing '' to a parameter that should be INTEGER

### ISSUE THREAD

**Issue by daveisfera** [vitaly-t/pg-promise#750]
### Expected behavior
Set to `NULL` or an error raised with an indication of the problem

### Actual behavior
A `spex` stacktrace is shown

### Steps to reproduce
Run a query with `''` as a parameter that should be `INTEGER`, like the following query `DELETE FROM mytest WHERE (id) IN ($1^)`

The error is the following:
```
{
    "name": "BatchError",
    "data": [
        {
            "success": false,
            "result": {
                "length": 91,
                "name": "error",
                "severity": "ERROR",
                "code": "22P02",
                "position": "70",
                "file": "int8.c",
                "line": "126",
                "routine": "scanint8"
            }   
        }   
    ],  
    "first": {
        "length": 91,
        "name": "error",
        "severity": "ERROR",
        "code": "22P02",
        "position": "70",
        "file": "int8.c",
        "line": "126",
        "routine": "scanint8"
    },  
    "stat": {
        "total": 1,
        "succeeded": 0,
        "failed": 1, 
        "duration": 2
    },  
    "stack": "BatchError: invalid input syntax for integer: \"\"
    at check (/usr/src/app/node_modules/spex/lib/ext/batch.js:135:32)
    at step (/usr/src/app/node_modules/spex/lib/ext/batch.js:109:17)
    at /usr/src/app/node_modules/spex/lib/ext/batch.js:83:17
    at /usr/src/app/node_modules/spex/lib/utils/index.js:62:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "type": "Error",
    "msg": "invalid input syntax for integer: \"\""
}
```

### Environment

* Version of pg-promise: 10.6.0
* OS type (Linux/Windows/Mac): macOS 10.15.6
* Version of Node.js: 12.18.3

**Comment by vitaly-t** [comment]
Everything here is by design, no issues. It is your expectation that's wrong.

Batch gives you status for all promises it attempts to resolve, which is essential to see what went wrong.

**Comment by daveisfera** [comment]
👍
