### ISSUE TITLE
Out-dated docs: `initOptions.connectionString` doesn't work

### ISSUE THREAD

**Issue by vjpr** [vitaly-t/pg-promise#788]
From: https://github.com/vitaly-t/pg-promise/wiki/Connection-Syntax#connection-string

```
const cn = {
    connectionString: 'postgres://...',
    max: 30
};

const db = pgp(cn);
```

```
Error: Option "connectionString" is not recognized.
    at assertOptions (/xxx/node_modules/.pnpm/assert-options@0.7.0/node_modules/assert-options/dist/src/index.js:16:23)
    at $main (/xxx/node_modules/.pnpm/pg-promise@10.10.2/node_modules/pg-promise/lib/main.js:194:15)
```

### Environment

* Version of pg-promise: ^10.10.2
* OS type (Linux/Windows/Mac): mac
* Version of Node.js: 16

**Comment by vjpr** [comment]
I was using it incorrectly...
