### ISSUE TITLE
10.15.1 crash on NodeJS 12

### ISSUE THREAD

**Issue by MrJibus** [vitaly-t/pg-promise#853]
### Expected behavior
Normal behavior

### Actual behavior
NodeJS crash
PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/usr/src/app/node_modules/pg-promise/lib/database.js:21:12)
at Module._compile (internal/modules/cjs/loader.js:999:30)
/usr/src/app/node_modules/pg-promise/lib/query.js:163
err.query = err.query ?? query;
^
SyntaxError: Unexpected token '?'

### Steps to reproduce
Install 10.15.1 version of pg-promise

### Environment

* Version of pg-promise: 10.15.1
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 12.20 with PM2

**Comment by vitaly-t** [comment]
Sorry, didn't check that coalescence operators were added in Node v14.

Fixed in [v10.15.2](https://github.com/vitaly-t/pg-promise/releases/tag/10.15.2).
